"""Change user_id_fk to user_id

Revision ID: 2297571dce37
Revises: 94cc102d63ae
Create Date: 2021-08-13 22:06:28.646959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2297571dce37'
down_revision = '94cc102d63ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'user_id_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id_fk', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id_fk'], ['id'])
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
